//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiTN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THI_TN;Initial Catalog=TN_CSDLPT;User ID=sa;Password=123456;TrustServ" +
            "erCertificate=True")]
        public string TN_CSDLPTConnectionString {
            get {
                return ((string)(this["TN_CSDLPTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OE056AS\\SERVER1;Initial Catalog=TN_CSDLPT;Persist Security Info=True;User ID=sa;Password=123456;Encrypt=True;TrustServerCertifi" +
            "cate=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN\\SERVER1;Initial Catalog=TN_CSDLPT;User ID=sa;Password=123456;Tr" +
            "ustServerCertificate=True")]
>>>>>>> df5352db4303b5f046be84e6165b1267013c9353
        public string TN_CSDLPTConnectionString1 {
            get {
                return ((string)(this["TN_CSDLPTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OE056AS;Initial Catalog=TN_CSDLPT;Persist Security Info=True;" +
            "User ID=sa;Password=123456;Encrypt=True;TrustServerCertificate=True")]
        public string TN_CSDLPTConnectionString2 {
            get {
                return ((string)(this["TN_CSDLPTConnectionString2"]));
            }
        }
    }
}
