CREATE PROCEDURE sp_Bang_Diem_Mon_Hoc
@MALOP CHAR(15), @MAMH CHAR(5), @LAN INT
AS
BEGIN
	DECLARE @MAGVDK INT

	SELECT @MAGVDK = MAGVDK
	FROM GIAOVIEN_DANGKY
	WHERE MALOP = @MALOP AND MAMH = @MAMH AND LAN = @LAN

	SELECT 
		SV.MASV AS [Mã Sinh Viên], 
		SV.HO + ' ' + SV.TEN AS [Họ Tên Sinh Viên], 
		BD.DIEM AS [Điểm],
		CASE 
			WHEN BD.DIEM >= 9.0 THEN 'A'
			WHEN BD.DIEM >= 7.0 THEN 'B'
			WHEN BD.DIEM >= 5.0 THEN 'C'
			WHEN BD.DIEM >= 3.0 THEN 'D'
			ELSE 'F'
		END AS [Điểm Chữ],
		BD.NGAYTHI AS [Ngày Thi]
	FROM 
		BANGDIEM BD
		JOIN SINHVIEN SV ON BD.MASV = SV.MASV
	WHERE 
		BD.MAGVDK = @MAGVDK
	ORDER BY 
		SV.HO, SV.TEN

END