USE [TN_CSDLPT]
GO

/****** Object:  StoredProcedure [dbo].[sp_xemKQThiSV]    Script Date: 6/23/2024 4:41:11 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[sp_xemKQThiSV]
	@MASV char(8),
	@MAMH char(5),
	@LAN smallint
AS
BEGIN
	SELECT 
    CT_BAITHI.STT,
    CT_BAITHI.CAUHOI,  
    BODE_TMP.NOIDUNG,
    CASE 
        WHEN CT_BAITHI.A = 'A' THEN BODE_TMP.A 
        WHEN CT_BAITHI.A = 'B' THEN BODE_TMP.B 
        WHEN CT_BAITHI.A = 'C' THEN BODE_TMP.C 
        WHEN CT_BAITHI.A = 'D' THEN BODE_TMP.D 
    END AS A,
    CASE 
        WHEN CT_BAITHI.B = 'A' THEN BODE_TMP.A 
        WHEN CT_BAITHI.B = 'B' THEN BODE_TMP.B 
        WHEN CT_BAITHI.B = 'C' THEN BODE_TMP.C 
        WHEN CT_BAITHI.B = 'D' THEN BODE_TMP.D 
    END AS B,
    CASE 
        WHEN CT_BAITHI.C = 'A' THEN BODE_TMP.A 
        WHEN CT_BAITHI.C = 'B' THEN BODE_TMP.B 
        WHEN CT_BAITHI.C = 'C' THEN BODE_TMP.C 
        WHEN CT_BAITHI.C = 'D' THEN BODE_TMP.D 
    END AS C,
    CASE 
        WHEN CT_BAITHI.D = 'A' THEN BODE_TMP.A 
        WHEN CT_BAITHI.D = 'B' THEN BODE_TMP.B 
        WHEN CT_BAITHI.D = 'C' THEN BODE_TMP.C 
        WHEN CT_BAITHI.D = 'D' THEN BODE_TMP.D 
    END AS D,
	CT_BAITHI.DAP_AN AS DA_CHON,
	CASE 
        WHEN CT_BAITHI.A = BODE_TMP.DAP_AN THEN 'A' 
        WHEN CT_BAITHI.B = BODE_TMP.DAP_AN THEN 'B' 
        WHEN CT_BAITHI.C = BODE_TMP.DAP_AN THEN 'C' 
        WHEN CT_BAITHI.D = BODE_TMP.DAP_AN THEN 'D'
    END AS DAP_AN
	FROM (
		SELECT MABD, MASV
		FROM BANGDIEM
		WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN AND DIEM IS NOT NULL
	) AS BD_TMP
	JOIN CT_BAITHI
	ON BD_TMP.MABD = CT_BAITHI.MABD
	JOIN (
		SELECT CAUHOI, NOIDUNG, A, B, C, D, DAP_AN 
		FROM BODE
	) AS BODE_TMP
	ON CT_BAITHI.CAUHOI = BODE_TMP.CAUHOI
	ORDER BY STT
END




GO


